name: librecad
version: '2.2.1-rc4'
grade: stable
base: core22
confinement: strict
license: GPL-2.0
summary: "librecad: is a 2D open source CAD"
compression: lzo
description: |
        LibreCAD is a cross-platform 2D CAD program written in C++17. It can read DXF/DWG files
        and can write DXF/PDF/SVG files. It supports point/line/circle/ellipse/parabola/spline
        primitives. The user interface is highly customizable, and has dozens of translations.
        Code repository:
        https://www.github.com/LibreCAD/LibreCAD
environment:
        QT_QPA_PLATFORMTHEME: gtk3
        LD_LIBRARY_PATH: $SNAP/usr/local/lib/:$SNAP/usr/lib/x86_64-linux-gnu/:$SNAP/usr/lib64/:$LD_LIBRARY_PATH

apps:
        librecad:
                command: usr/bin/librecad
                plugs:
                  - desktop
                  - home
                  - wayland
                  - x11
                desktop: usr/share/applications/org.librecad.librecad.desktop
                common-id: org.librecad.librecad.desktop
                extensions:
                  - kde-neon

parts:
        librecad:
                plugin: qmake
                qmake-parameters:
                  - "QMAKE_CFLAGS+=-march=x86_64"
                  - "QMAKE_CXXFLAGS+=-march=x86-64"
                source: .
                build-packages:
                        - build-essential
                        - qtbase5-dev
                        - qttools5-dev
                        - qttools5-dev-tools
                        - librsvg2-bin
                        - libqt5waylandclient5-dev
                        - libfreetype6-dev
                        - libicu-dev
                        - libqt5opengl5-dev
                        - libcairo2-dev
                        - libpango-1.0-0
                        - libpango1.0-dev
                        - libboost-dev
                        - libqt5svg5-dev
                        - libgtest-dev
                        - libcurl4-gnutls-dev
                        - libgtk-3-dev
                        - rsync

                stage-packages:
                        - libfreetype6
                        - libqt5gui5
                        - libqt5printsupport5
                stage:
                  - -usr/share/pkgconfig

                override-stage: |
                        #echo "1"
                        #echo $PWD 
                        #find .. -type f -name librecad
                        export SRC_DIR=../parts/librecad/build/unix
                        echo $SNAPCRAFT_STAGE
                        mkdir -p $SNAPCRAFT_STAGE/usr/bin
                        mkdir -p $SNAPCRAFT_STAGE/usr/share/librecad
                        mkdir -p $SNAPCRAFT_STAGE/usr/share/applications
                        mkdir -p usr/bin
                        mkdir -p usr/share/librecad
                        cp -a $SRC_DIR/librecad $SNAPCRAFT_STAGE/usr/bin/
                        cp -a $SRC_DIR/ttf2lff $SNAPCRAFT_STAGE/usr/bin/
                        cp -a $SRC_DIR/resources/* $SNAPCRAFT_STAGE/usr/share/librecad/
                        export DESKTOP_DIR=../parts/librecad/src/desktop
                        cp -a $DESKTOP_DIR/*.desktop $SNAPCRAFT_STAGE/usr/share/applications/org.librecad.librecad.desktop
                        cp -a $DESKTOP_DIR/org.librecad.*.xml $SNAPCRAFT_STAGE/usr/share/applications/org.librecad.librecad.xml
                        snapcraftctl stage 
                override-prime: |
                        rsync -av ../stage/* ./
                        snapcraftctl prime 

