name: librecad
version: '2.2.1.1-rc'
grade: stable
base: core22
confinement: strict
license: GPL-2.0
summary: "librecad: is a 2D open source CAD"
compression: lzo
description: |
  LibreCAD is a cross-platform 2D CAD program written in C++17. It can read DXF/DWG files
  and can write DXF/PDF/SVG files. It supports point/line/circle/ellipse/parabola/spline
  primitives. The user interface is highly customizable, and has dozens of translations.
  Code repository:
  https://www.github.com/LibreCAD/LibreCAD
environment:
  LD_LIBRARY_PATH: $SNAP/usr/local/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/usr/lib64/:$LD_LIBRARY_PATH

apps:
  librecad:
    command: usr/bin/librecad
    plugs:
      - home
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - unity7
      - x11
    desktop: usr/share/applications/org.librecad.librecad.desktop
    common-id: org.librecad.librecad.desktop
    extensions:
      - kde-neon #kde-neon-6
      
plugs:
  desktop:
    mount-host-font-cache: false
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  kf5-core22-sdk:
    content: kf5-core22-sdk
    interface: content
    default-provider: kf5-core22-sdk
    target: $SNAP/kf5
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes

parts:
  librecad:
    plugin: cmake #qmake
    #qmake-parameters:
    #  - "QMAKE_CFLAGS+=-march=x86_64"
    #  - "QMAKE_CXXFLAGS+=-march=x86-64"
    build-environment:
      - QT_SELECT: qt5 #qt6
    source: .
    build-packages:
      - build-essential
      - qtbase5-dev #qt6-base-dev
      - qttools5-dev #qt6-tools-dev
      #- qttools5-dev-tools #qt6-tools-dev-tools
      - librsvg2-bin
      - libqt5waylandclient5-dev #qt6-wayland-dev
      - libfreetype6-dev
      - libicu-dev
      - libqt5opengl5-dev #libqt6opengl6-dev
      #- libcairo2-dev
      #- libpango-1.0-0
      #- libpango1.0-dev
      - libboost-dev
      - libgl1-mesa-dev # avoid openGL fatal error: GL/gl.h: No such file or directory
      - libqt5svg5-dev #libqt6svg6-dev
      #- libgtest-dev
      #- libcurl4-gnutls-dev
      #- libgtk-3-dev
      - qt3d5-dev
      - rsync
      
    override-build: |
      # craftctl default
      export QT_SELECT=qt5
      cmake ../../..
      #/snap/kf5-5-113-qt-5-15-11-core22-sdk/current/usr/lib/qt5/bin/qmake -r 'QMAKE_CFLAGS+=-isystem $CRAFT_STAGE/usr/include' 'QMAKE_CXXFLAGS+=-isystem $CRAFT_STAGE/usr/include' 'QMAKE_LFLAGS+=-L$CRAFT_STAGE/lib -L$CRAFT_STAGE/usr/lib -L$CRAFT_STAGE/usr/lib/x86_64-linux-gnu'
      make -r -j$(nproc)

    #stage-packages:
      #- libfreetype6
      #- libqt5gui5 #libqt6gui6
      #- libqt5printsupport5 #libqt6printsupport6
    stage:
      - -usr/share/pkgconfig

    override-stage: |
      ls
      export SRC_DIR=../parts/librecad/build/
      echo $CRAFT_STAGE
      mkdir -p $CRAFT_STAGE/usr/bin
      mkdir -p $CRAFT_STAGE/usr/share/icons
      mkdir -p $CRAFT_STAGE/usr/share/librecad/resources/qm
      mkdir -p $CRAFT_STAGE/usr/share/applications
      mkdir -p usr/bin
      mkdir -p usr/share/librecad
      cp -a $SRC_DIR/librecad $CRAFT_STAGE/usr/bin/
      #cp -a $SRC_DIR/ttf2lff $CRAFT_STAGE/usr/bin/
      cp -a $SRC_DIR/*.qm $CRAFT_STAGE/usr/share/librecad/resources/qm
      rsync -vaut ../librecad/support/* $CRAFT_STAGE/usr/share/librecad/resources/
      export DESKTOP_DIR=../parts/librecad/src/desktop
      find ../CI -type f -name librecad.svg -exec cp -av '{}' $CRAFT_STAGE/usr/share/icons/ ';'
      cp -a $DESKTOP_DIR/*.desktop $CRAFT_STAGE/usr/share/applications/org.librecad.librecad.desktop
      sed -i'' -e 's:^\s*Icon=.*$:Icon=/usr/share/icons/librecad.svg:' $CRAFT_STAGE/usr/share/applications/org.librecad.librecad.desktop
      cp -a $DESKTOP_DIR/org.librecad.*.xml $CRAFT_STAGE/usr/share/applications/org.librecad.librecad.xml
      craftctl default

    override-prime: |
      rsync -av ../stage/* ./
      craftctl default
