name: 2.2.0 bugfix builds
on:
  push:
    branches:
      - 2.2

jobs:
  BuildLinux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: '2.2'
          fetch-depth: 0

      - name: Install Qt and dependencies
        run: |
          sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.9-focal
          sudo apt-get -y update
          sudo apt-get -qq install qt512-meta-full libgl-dev libmuparser-dev libboost-dev libfreetype6-dev libicu-dev pkg-config qtchooser
          sudo cp CI/qt512.conf /usr/share/qtchooser/
          sudo ln -snf /usr/share/qtchooser/qt512.conf /usr/lib/x86_64-linux-gnu/qtchooser/default.conf

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        with:
          boost_version: 1.75.0
          boost_install_dir: '${{ github.workspace }}/'
          platform_version: 20.04

      - name: Install Clang
        run: |
          sudo apt-get -qq install clang-10 clang-tools-10

      - name: Build
        run: |
          export CC=gcc
          qmake -r librecad.pro CONFIG+=debug_and_release PREFIX=/usr BOOST_DIR=${{ github.workspace }}/boost/boost
          make release -j$(nproc)

      - name: Create AppImage
        run: |
          find unix/
          ./CI/build-appimg.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: assets.AppImage
          path: LibreCAD*.AppImage
          retention-days: 2

  BuildMacOS:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Qt5 and dependencies
        run: |
          brew install boost qt@5
          brew link qt@5 --force

      - name: Build and packaging
        run: |
          scripts/build-osx.sh
          mv LibreCAD.dmg LibreCAD-`git describe --always`.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: assets.dmg
          path: LibreCAD*.dmg
          retention-days: 2

  BuildWindows:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Uninstall incorrect mingw
        run: |
          choco uninstall mingw --force
          choco uninstall strawberryperl --force

      - name: Install MinGW7.3 32-bit
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.12.11'
          host: 'windows'
          target: 'desktop'
          dir: ..
          arch: 'win32_mingw73'

      - name: Install boost
        shell: bash
        run: |
          curl -# -L -o boost.7z https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.7z
          7z x -o. -y boost.7z
          mv boost_1_75_0 ../boost
          rm boost.7z

      - name: Build
        run: |
          set PATH=c:\msys64\mingw32\bin;%PATH%
          copy CI\custom-win.pri custom.pri
          copy CI\custom-win.nsh scripts\postprocess-windows\custom.nsh
          echo SET:
          set
          pushd "${{ github.workspace }}\scripts"
          build-windows.bat
        shell: cmd

      - name: Rename installer
        run: |
          mv generated/LibreCAD-Installer.exe LibreCAD-Installer-`git describe --always`.exe
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: assets.exe
          path: LibreCAD-Installer*.exe
          retention-days: 2

  UpdateAssets:
    if: github.repository_owner == 'LibreCAD'
    needs: [BuildLinux, BuildMacOS, BuildWindows]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch artifacts
        uses: actions/download-artifact@v4

      - name: Delete previous assets
        run: gh release delete "2.2.0-latest" -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # https://github.com/marketplace/actions/gh-release
      - name: Upload latest pre-release
        uses: "softprops/action-gh-release@v2"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "2.2.0-latest"
          prerelease: true
          generate_release_notes: true
          name: "Continuous Build 2.2.0.x"
          files: |
            assets.AppImage/LibreCAD*.*
            assets.dmg/LibreCAD*.*
            assets.exe/LibreCAD*.*
            LICENSE
